autolabeler:
  - label: 'rust'
    files:
      - 'rust/**/*'
  - label: 'python'
    files:
      - 'python/**/*'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
