_extends: release-drafter

name-template: py-$RESOLVED_VERSION
tag-template: py-$RESOLVED_VERSION
tag-prefix: py-

include-labels:
  - python

template: |
  # New Polars release for Python!

  $CHANGES

  ## Full changelog
  https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...py-$RESOLVED_VERSION

  ## Contributors
  Many thanks to all our contributors for making this release possible!
  $CONTRIBUTORS
