name-template: 'rs-v$RESOLVED_VERSION 🌈'
tag-template: 'rs-v$RESOLVED_VERSION'

include-labels:
  - 'rust'

categories:
  - title: 'Features 🚀'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug fixes 🐛'
    labels: 'fix'
  - title: 'Maintenance 🧰'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

autolabeler:
  - label: 'rust'
    files:
      - 'rust/**/*'
  - label: 'python'
    files:
      - 'python/**/*'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
  - label: 'fix'
    branch:
      - '/fix\/.+/'

template: |
  ## Changes

  $CHANGES
