_extends: test-release-drafter:.github/release-drafter.yml

name-template: py-$RESOLVED_VERSION
tag-template: py-$RESOLVED_VERSION
tag-prefix: py-

include-labels:
  - python

header: '# New Polars release for Python!'
