categories:
  - title: Highlights 🏆
    labels: highlight
  - title: Breaking changes ⚠️
    labels: breaking
  - title: Performance improvements 🚀
    labels: performance
  - title: Enhancements ✨
    labels: enhancement
  - title: Bug fixes 🐛
    labels: fix
  - title: Other improvements 🛠️
    label: chore
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  minor:
    labels: breaking
  default: patch

autolabeler:
  - label: rust
    files:
      - polars/
  - label: python
    files:
      - py-polars/
  - label: performance
    branch:
      - '/^perf(ormance)?\/.*/'
  - label: enhancement
    branch:
      - '/^enhance(ment)?\/.*/'
      - '/^feat(ure)?\/.*/'
  - label: fix
    branch:
      - '/^(bug)?fix\/.*/'
  - label: chore
    branch:
      # Match anything else
      - '/^(?!(perf(ormance)?\/|enhance(ment)?\/|feat(ure)?\/|(bug)?fix\/)).*/'

template: |
  $CHANGES

  Thank you to all our contributors for making this release possible!
  $CONTRIBUTORS
