name-template: py-$RESOLVED_VERSION
tag-template: py-$RESOLVED_VERSION
tag-prefix: py-

include-labels:
  - python

categories:
  - title: Features 🚀
    labels: feature
  - title: Bug fixes 🐛
    labels: fix
  - title: Other 🛠️
    label: chore
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  minor:
    labels: breaking
  default: patch

template: |
  # New Polars release for Python!

  $CHANGES

  **Full changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...py-$RESOLVED_VERSION
