name-template: py-v$RESOLVED_VERSION
tag-template: py-v$RESOLVED_VERSION
tag-prefix: py-v

include-labels:
  - python

categories:
  - title: Features 🚀
    labels: feature
  - title: Bug fixes 🐛
    labels: fix
  - title: Maintenance 🧰
    label: chore
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  minor:
    labels: breaking
  default: patch

template: $CHANGES
