name-template: 'py-v$RESOLVED_VERSION'
tag-template: 'py-v$RESOLVED_VERSION'

include-labels:
  - 'python'

categories:
  - title: 'Features 🚀'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug fixes 🐛'
    labels: 'fix'
  - title: 'Maintenance 🧰'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  minor:
    labels:
      - 'breaking'
  default: patch

template: |
  ## Changes

  $CHANGES
