name: Update release draft

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Draft Rust release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-rust.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Draft Python release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-python.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
