name: Pull request labeler

on: pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Label pull request
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-rust.yml
          disable-releaser: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
